# Generated by Django 4.1.3 on 2022-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_db_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images')),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='home_page_db_1',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
